Origin/dev/cha 20 UI elements
abarakkadabra/chapaev-in-london pull request #1
Opened 2022-10-28 10:52 UTC by khomch

### Созданы компоненты Input и Button, подключен sass

### Скриншот
<img width="1512" alt="Screenshot 2022-10-28 at 13 51 57" src="https://user-images.githubusercontent.com/65286114/198570611-4e18842b-d5e8-47cf-93ad-a803c7687c59.png">

2022-10-28 11:35 UTC, abarakkadabra reviewed
Привет! В общем всё ОК. оставил 2 коммента по зависимостям и обязательным полям.

2022-10-28 11:35 UTC, abarakkadabra commented on packages/client/src/components/UI-elements/Input/Input.tsx
> +  name: string | undefined;
Если поля name, placeholder обязательные, они не должны быть undefined. Предлагаю оставить только string.

2022-10-28 11:35 UTC, abarakkadabra commented on packages/client/package.json
> +    "react-dom": "^18.2.0",
В 1 модуле ревьюеры рекомендовали фиксировать все зависимости. Предлагаю здесь так же зафиксировать.

2022-10-28 12:11 UTC, abarakkadabra commented
ОК, замечаний нет

2022-10-29 13:01 UTC, AntonVolkov71 commented
[packages/client/src/components/UI-elements/Button/Button.tsx](url)
- type относится к стилям, в Input относится к типу элемента. Тогда везде  type - тип элемента. variant:Variant  - цвет primary, error и так далее.
type Variant = 'primary' | 'secondary' | 'success' | 'warning' | 'danger' | 'light' | 'link'
-  Тоже самое в Input добавить цвета
- ` ${props.type === 'primary' && styles.button_primary}
        ${props.type === 'secondary' && styles.button_secondary}
        ${props.type === 'inactive' && styles.button_inactive}
        ${props.type === 'accent' && styles.button_accent}
        ${props.size === 'small' && styles.button_small}
        ${props.size === 'medium' && styles.button_medium}
        ${props.size === 'large' && styles.button_large}`

 можно сократить до 
        ${styles[`${buttonClassName}_${props.type}`]}
        ${styles[`${buttonClassName}_${props.size}`]}
- наименование прослушек onClick, onChange - в компоненте UI  предлагаю так и оставить, а не handleChange, ибо единообразие
- нет возможности добавить своих стилей UI в компонент, например хочу оставить только нижний бордер и стиль как у всех. 
- disabled  - у кнопки и инпута у селекта, у всех где есть ввод или изменения

2022-10-29 14:55 UTC, AndreyTsvetkov requested changes
Чутка вопросов по наименованию, давайте обсудим может даже в чате  и примем общий стандарт для проекта.

2022-10-29 14:55 UTC, AndreyTsvetkov commented on packages/client/src/components/UI-elements/Button/Button.tsx
> +export interface IButtonInterface {
Немножко вопросов по неймингу

В TS, в отличие от C#, не принято ставить префикс І, и к тому же он дублируется со словом Interface.

В свою очередь суффикс Interface тоже не нужен, и он дублирует саму сущность, мы же не называем каждый класс ХххClass, а функцию XxxFunction

Обычно это называется ButtonProps, и обычно это просто type, ведь тут не планируется какой-то полиморфизм, чтобы вводить именно interface

2022-10-29 14:55 UTC, AndreyTsvetkov commented on packages/client/src/components/UI-elements/Input/Input.tsx
> +interface IInputInterface {
Аналогично

2022-10-30 09:49 UTC, merged