add Profile page
abarakkadabra/chapaev-in-london pull request #14
Opened 2022-11-19 14:01 UTC by khomch

### Какую задачу решаем

Добавлена страница профиля с возможностью изменения аватара / данных пользователя / пароля / логаута. 

### Скриншоты/видяшка (если есть)
<img width="1512" alt="Screenshot 2022-11-19 at 17 01 37" src="https://user-images.githubusercontent.com/65286114/202854379-c8bf1e34-6949-4c52-8ae2-2b8ac76a9f9d.png">

### TBD (если есть)

2022-11-21 11:42 UTC, abarakkadabra reviewed
Привет! Хорошо сделано! Несколько замечаний:
 - Нужно добавить обработчик клика в случае, если аватара нет.
 - Если зайти в смену пароля и нажать на profile в шапке, то страница не обновится, только по кнопке назад.
 - После изменения пароля, если успешно, можно автоматически отправлять юзера обратно в профиль.
 - При выборе нового аватара, до подтверждения,  пропадает сам инпут. Лучше, если его будет видно.
![Capture](https://user-images.githubusercontent.com/7449676/203041437-88d8d6c4-3f5f-4091-8014-5251dc130d33.PNG)

- В качестве предложения: можно ли как-то декомпозировать profile? Кажется, что 300 строк это много (может быть и нет).

2022-11-21 11:42 UTC, abarakkadabra commented on packages/client/src/components/UI-elements/Avatar/Avatar.tsx
> +    return <div className={`${styles.avatar} ${styles.avatar__noAvatar} ${styles.avatar_edit}`}></div>
если аватара нет, то тоже нужен обработчик клика

2022-11-22 11:32 UTC, khomch commented on packages/client/src/components/UI-elements/Avatar/Avatar.tsx
> +    return <div className={`${styles.avatar} ${styles.avatar__noAvatar} ${styles.avatar_edit}`}></div>
++

2022-11-22 20:56 UTC, AndreyTsvetkov requested changes

2022-11-22 20:56 UTC, AndreyTsvetkov commented on packages/client/src/pages/profile/Profile.tsx
> +  const [changeDataOrPassword, setChangeDataOrPassword] = useState('data')
Я бы здесь написал `useState('data' as 'data' | 'password')`  и таким образом защитился от опечаток при работе с этим данным, а главное - так сразу при чтении дал бы понять читающему, что это enum (если уж не делаем прям настоящий enum)

2022-11-22 20:56 UTC, AndreyTsvetkov commented on packages/client/src/pages/profile/Profile.tsx
> +  const handleChangePasswordButtonClick = () => {
а эту штуку я бы назвал `toggleDataOrPassword`; зачем ей дублировать название свойства у компонента ниже? зато бы читалось логично: `handleChangePasswordButtonClick={toggleDataOrPassword}`

2022-11-22 20:56 UTC, AndreyTsvetkov commented on packages/client/src/store/Authorization.ts
> +  signIn(
и туда же про нестрелочные методы, предлагаю запретить их

2022-11-23 11:20 UTC, khomch commented on packages/client/src/pages/profile/Profile.tsx
> +  const handleChangePasswordButtonClick = () => {
++

2022-11-23 11:23 UTC, khomch commented on packages/client/src/store/Authorization.ts
> +  signIn(
++

2022-11-24 10:48 UTC, merged