add game engine
abarakkadabra/chapaev-in-london pull request #7
Opened 2022-11-05 17:47 UTC by yurybabaev

### Добавлен игровой движок

2022-11-07 11:20 UTC, abarakkadabra reviewed
Привет! Очень классно сделано! Оставил несколько предложений, посмотри плз.

2022-11-07 11:20 UTC, abarakkadabra commented on packages/client/src/components/Game/Game.tsx
> +    const gameType = new GameTypeAi(game)
стоит добавить возможность выбрать тип игры

2022-11-07 11:20 UTC, abarakkadabra commented on packages/client/src/components/Game/Game.tsx
> +import { Game as GameEngine } from '../../gameEngine/Game'
Может быть переименовать файл и класс в Game Engine? чтобы не было путанности в компоненте Game.tsx и движке Game.ts

2022-11-07 11:20 UTC, abarakkadabra commented on packages/client/src/gameEngine/Game.ts
> +        result.winnerId = this.getWinnerId();
стоит проверять победителя только если нет шашек или if(this.getWinnerId())

2022-11-07 11:20 UTC, abarakkadabra commented on packages/client/src/gameEngine/GameType.ts
> +    this.game.checkers.forEach((checker) => {
Я думаю не стоит переворачивать доску, так как это сильно запутывает игроков. Предлагаю убрать эту конструкцию и оставлять второго игрока всегда сверху.

2022-11-07 11:20 UTC, abarakkadabra commented on packages/client/src/gameEngine/GameVisualizer.ts
> +};
стоит вынести различные цветовые темы в отдельную сущность и дать возможность пользователю менять их?

2022-11-07 11:20 UTC, abarakkadabra commented on packages/client/src/gameEngine/Vector.ts
> +  public magnutude() {
похоже на опечатку, должно быть magnitude

2022-11-08 15:50 UTC, yurybabaev commented on packages/client/src/components/Game/Game.tsx
> +    const gameType = new GameTypeAi(game)
Обязательно, но это после того, как определимся с началом игры и подобным

2022-11-08 15:50 UTC, yurybabaev commented on packages/client/src/components/Game/Game.tsx
> +import { Game as GameEngine } from '../../gameEngine/Game'
Отличная идея, сделал

2022-11-08 15:51 UTC, yurybabaev commented on packages/client/src/gameEngine/Game.ts
> +        result.winnerId = this.getWinnerId();
А там функция внутри все проверяет и возвращает null, если победителя пока нет

2022-11-08 15:52 UTC, yurybabaev commented on packages/client/src/gameEngine/GameType.ts
> +    this.game.checkers.forEach((checker) => {
Это сделано только для режима hot seat, когда игроки по очереди играют за одним компьютером. Реализация этой функции для игры против ИИ не делает ничего

2022-11-08 15:52 UTC, yurybabaev commented on packages/client/src/gameEngine/GameVisualizer.ts
> +};
Это обязательно стоит сделать, но позже, когда у нас будет выбор темы

2022-11-08 15:52 UTC, yurybabaev commented on packages/client/src/gameEngine/Vector.ts
> +  public magnutude() {
Точняк, поправил

2022-11-16 11:18 UTC, AndreyTsvetkov requested changes
я бы вообще добавил в настройки линтера запрет не стрелочных функций

2022-11-16 11:18 UTC, AndreyTsvetkov commented on packages/client/src/gameEngine/Checker.ts
> +  contains(point: Vector) {
нет причин использовать в классе НЕ стрелочные функции (да и не только в классе, но тут особенно)

и далее аналогично

иначе гарантированно получим проблемы с this при передаче ссылки на метод в самый неожиданный момент

2022-11-22 20:35 UTC, AndreyTsvetkov requested changes
Остается вопрос про нестрелочные функции

2022-11-24 11:02 UTC, merged