add SignIn and SignUp
abarakkadabra/chapaev-in-london pull request #9
Opened 2022-11-09 13:12 UTC by abarakkadabra

### Какую задачу решаем
Добавил страницы Регистрации и входа 

### Скриншоты/видяшка (если есть)

### TBD (если есть)
валидация, тексты ошибок. Это лучше сделать после добавления всех страниц.

2022-11-14 15:45 UTC, AntonVolkov71 reviewed
Привет, всё круто, кроме пару моментов, которые я описал в комментариях. 
Про валидацию и вывод ошибки, считаю сделать сразу, так как для все реализовано для этого, и не хочется потом доделывать еще раз эти компоненты.

На обсуждение: 
- формы и внутренние элементы вынести в UI элементы, чтобы не делать новую форму в каждом компоненте
 например, 
  - компонент formUIона принимает в качестве дочерних элементов набор элементов (input, button и так далее), отдает "наверх" прослушку по submit
  - компонент inputUI - он принимает type, name, value, error, minLength и т.д., в этом компоненте добавляется label, span с ошибкой. отдает "наверх" прослушку по change
  - компонент button по аналогии с input
  - компонент emailUI - принимает внутрь компонент InputUI со всеми данными (type, name, value, error, minLength и т.д.).
  - emailUI, phoneUI, loginUI, passwordUI и другие оп аналогии с emailUI
  - и теперь можно использовать форму с любыми компонентами emailUI, phoneUI и т.д.

И не придется настраивать форму и внутренние компоненты(а также стили,  обработку ошибок) в каждом компоненте. Например, профиль очень похож на авторизацию

2022-11-14 15:45 UTC, AntonVolkov71 commented on packages/client/src/components/nav/Nav.tsx
> +}
Все пути навигации взять из enum RoutePaths

2022-11-14 15:45 UTC, AntonVolkov71 commented on packages/client/src/pages/signin/SignIn.tsx
> +}
- Input & Buttton поместить в форму, и тип кнопки submit. 
- Вход не только по клику кнопки, но и по нажатия на ENTER.  
- Валидацию можно добавить на длину вводимых символов, так как обязательное условие по заданию
- Обработку ошибок тоже можно сразу сделать, API возвращает ошибку, поле errorText в компоненте можно подписаться на него

2022-11-14 21:32 UTC, abarakkadabra commented on packages/client/src/components/nav/Nav.tsx
> +}
++

2022-11-14 21:34 UTC, abarakkadabra commented on packages/client/src/pages/signin/SignIn.tsx
> +}
Переместил в форму, повесил на submit. 
Валидацию прикрутил, но криво.

2022-11-16 11:11 UTC, AndreyTsvetkov requested changes

2022-11-16 11:11 UTC, AndreyTsvetkov commented on packages/client/src/components/UI-elements/partials/PasswordUI/PasswordUI.tsx
> +  return (
кажется тут что-то надо раскомментить

2022-11-16 11:52 UTC, AndreyTsvetkov approved these changes

2022-11-16 13:17 UTC, merged